#!/usr/bin/env python3
"""Generate a clean iOS-App.xcodeproj for TrustNetValidator"""

import os
import uuid

# Create minimal but valid pbxproj
pbxproj_content = """// !$*UTF8*$!
{
	archiveVersion = 1;
	classes = {
	};
	objectVersion = 54;
	objects = {
		FA0001B02BD5A1C40027F4A6 /* App.swift */ = {isa = PBXFileReference; fileEncoding = 4; lastKnownFileType = sourcecode.swift; path = "TrustNetValidator/App.swift"; sourceTree = "<group>"; };
		FA0001B12BD5A1C40027F4A6 /* ContentView.swift */ = {isa = PBXFileReference; fileEncoding = 4; lastKnownFileType = sourcecode.swift; path = "TrustNetValidator/ContentView.swift"; sourceTree = "<group>"; };
		FA0001B22BD5A1C40027F4A6 /* PassportValidator.swift */ = {isa = PBXFileReference; fileEncoding = 4; lastKnownFileType = sourcecode.swift; path = "Sources/PassportValidator.swift"; sourceTree = "<group>"; };
		FA0001B32BD5A1C40027F4A6 /* Assets.xcassets */ = {isa = PBXFileReference; lastKnownFileType = folder.assetcatalog; path = "TrustNetValidator/Assets.xcassets"; sourceTree = "<group>"; };
		FA0001B42BD5A1C40027F4A6 /* Info.plist */ = {isa = PBXFileReference; fileEncoding = 4; lastKnownFileType = text.plist.xml; path = "TrustNetValidator/Info.plist"; sourceTree = "<group>"; };
		FA0001C82BD5A1C40027F4A6 /* TrustNetValidator.app */ = {isa = PBXFileReference; explicitFileType = wrapper.application; includeInIndex = 0; path = TrustNetValidator.app; sourceTree = BUILT_PRODUCTS_DIR; };
		FA0001B62BD5A1C40027F4A6 /* Sources */ = {isa = PBXGroup; children = (FA0001B22BD5A1C40027F4A6, ); name = Sources; sourceTree = "<group>"; };
		FA0001B72BD5A1C40027F4A6 /* TrustNetValidator */ = {isa = PBXGroup; children = (FA0001B02BD5A1C40027F4A6, FA0001B12BD5A1C40027F4A6, FA0001B32BD5A1C40027F4A6, FA0001B42BD5A1C40027F4A6, ); path = TrustNetValidator; sourceTree = "<group>"; };
		FA0001B82BD5A1C40027F4A6 /* TrustNetValidator */ = {isa = PBXGroup; children = (FA0001B62BD5A1C40027F4A6, FA0001B72BD5A1C40027F4A6, ); sourceTree = "<group>"; };
		FA0001C72BD5A1C40027F4A6 /* Products */ = {isa = PBXGroup; children = (FA0001C82BD5A1C40027F4A6, ); name = Products; sourceTree = "<group>"; };
		FA0001C92BD5A1C40027F4A6 /* Sources */ = {isa = PBXSourcesBuildPhase; buildActionMask = 2147483647; files = (FA0001D12BD5A1C40027F4A6, FA0001D22BD5A1C40027F4A6, FA0001D32BD5A1C40027F4A6, ); runOnlyForDeploymentPostprocessing = 0; };
		FA0001CA2BD5A1C40027F4A6 /* Frameworks */ = {isa = PBXFrameworksBuildPhase; buildActionMask = 2147483647; files = (); runOnlyForDeploymentPostprocessing = 0; };
		FA0001CB2BD5A1C40027F4A6 /* Resources */ = {isa = PBXResourcesBuildPhase; buildActionMask = 2147483647; files = (FA0001D42BD5A1C40027F4A6, FA0001D52BD5A1C40027F4A6, ); runOnlyForDeploymentPostprocessing = 0; };
		FA0001D12BD5A1C40027F4A6 /* App.swift in Sources */ = {isa = PBXBuildFile; fileRef = FA0001B02BD5A1C40027F4A6; };
		FA0001D22BD5A1C40027F4A6 /* ContentView.swift in Sources */ = {isa = PBXBuildFile; fileRef = FA0001B12BD5A1C40027F4A6; };
		FA0001D32BD5A1C40027F4A6 /* PassportValidator.swift in Sources */ = {isa = PBXBuildFile; fileRef = FA0001B22BD5A1C40027F4A6; };
		FA0001D42BD5A1C40027F4A6 /* Assets.xcassets in Resources */ = {isa = PBXBuildFile; fileRef = FA0001B32BD5A1C40027F4A6; };
		FA0001D52BD5A1C40027F4A6 /* Info.plist in Resources */ = {isa = PBXBuildFile; fileRef = FA0001B42BD5A1C40027F4A6; };
		FA0001CC2BD5A1C40027F4A6 /* TrustNetValidator */ = {isa = PBXNativeTarget; buildConfigurationList = FA0001DD2BD5A1C40027F4A6; buildPhases = (FA0001C92BD5A1C40027F4A6, FA0001CA2BD5A1C40027F4A6, FA0001CB2BD5A1C40027F4A6, ); buildRules = (); dependencies = (); name = TrustNetValidator; productName = TrustNetValidator; productReference = FA0001C82BD5A1C40027F4A6; productType = "com.apple.product-type.application"; };
		FA0001BA2BD5A1C40027F4A6 /* Project object */ = {isa = PBXProject; attributes = {BuildIndependentTargetsInParallel = 1; LastSwiftUpdateCheck = 1430; LastUpgradeCheck = 1430; TargetAttributes = {FA0001CC2BD5A1C40027F4A6 = {CreatedOnToolsVersion = 14.3.1; }; }; }; buildConfigurationList = FA0001BD2BD5A1C40027F4A6; compatibilityVersion = "Xcode 9.3"; developmentRegion = en; hasScannedForEncodings = 0; knownRegions = (en, Base, ); mainGroup = FA0001B82BD5A1C40027F4A6; productRefGroup = FA0001C72BD5A1C40027F4A6; projectDirPath = ""; projectRoot = ""; targets = (FA0001CC2BD5A1C40027F4A6, ); };
		FA0001BD2BD5A1C40027F4A6 /* Build configuration list for PBXProject "TrustNetValidator" */ = {isa = XCConfigurationList; buildConfigurations = (FA0001DE2BD5A1C40027F4A6, FA0001DF2BD5A1C40027F4A6, ); defaultConfigurationIsVisible = 0; defaultConfigurationName = Release; };
		FA0001DD2BD5A1C40027F4A6 /* Build configuration list for PBXNativeTarget "TrustNetValidator" */ = {isa = XCConfigurationList; buildConfigurations = (FA0001E02BD5A1C40027F4A6, FA0001E12BD5A1C40027F4A6, ); defaultConfigurationIsVisible = 0; defaultConfigurationName = Release; };
		FA0001DE2BD5A1C40027F4A6 /* Debug */ = {isa = XCBuildConfiguration; buildSettings = {ALWAYS_SEARCH_USER_PATHS = NO; CLANG_ANALYZER_NONNULL = YES; CLANG_ANALYZER_NUMBER_OBJECT_CONVERSION = YES_AGGRESSIVE; CLANG_CXX_LANGUAGE_DIALECT = "c++20"; CLANG_CXX_LIBRARY = "libc++"; CLANG_ENABLE_MODULES = YES; CLANG_ENABLE_OBJC_ARC = YES; CLANG_ENABLE_OBJC_WEAK = YES; CLANG_WARN_BLOCK_CAPTURE_AUTORELEASING = YES; CLANG_WARN_BOOL_CONVERSION = YES; CLANG_WARN_COMMA = YES; CLANG_WARN_CONSTANT_CONVERSION = YES; CLANG_WARN_DEPRECATED_OBJC_IMPLEMENTATIONS = YES; CLANG_WARN_DIRECT_OBJC_ISA_USAGE = YES_ERROR; CLANG_WARN_DOCUMENTATION_COMMENTS = YES; CLANG_WARN_EMPTY_BODY = YES; CLANG_WARN_ENUM_CONVERSION = YES; CLANG_WARN_INFINITE_RECURSION = YES; CLANG_WARN_INT_CONVERSION = YES; CLANG_WARN_NON_LITERAL_NULL_CONVERSION = YES; CLANG_WARN_OBJC_IMPLICIT_RETAIN_SELF = YES; CLANG_WARN_OBJC_LITERAL_CONVERSION = YES; CLANG_WARN_OBJC_ROOT_CLASS = YES_ERROR; CLANG_WARN_QUOTED_INCLUDE_IN_FRAMEWORK_HEADER = YES; CLANG_WARN_RANGE_LOOP_ANALYSIS = YES; CLANG_WARN_STRICT_PROTOTYPES = YES; CLANG_WARN_SUSPICIOUS_MOVE = YES; CLANG_WARN_SUSPICIOUS_IMPLICIT_CONVERSION = YES; CLANG_WARN_UNREACHABLE_CODE = YES; CLANG_WARN__DUPLICATE_METHOD_MATCH = YES; COPY_PHASE_STRIP = NO; DEBUG_INFORMATION_FORMAT = dwarf; ENABLE_STRICT_OBJC_MSGSEND = YES; ENABLE_TESTABILITY = YES; GCC_C_LANGUAGE_DIALECT = gnu99; GCC_DYNAMIC_NO_PIC = NO; GCC_NO_COMMON_BLOCKS = YES; GCC_OPTIMIZATION_LEVEL = 0; GCC_PREPROCESSOR_DEFINITIONS = (DEBUG, "$(inherited)", ); GCC_WARN_64_TO_32_BIT_CONVERSION = YES; GCC_WARN_ABOUT_RETURN_TYPE = YES_ERROR; GCC_WARN_UNDECLARED_SELECTOR = YES; GCC_WARN_UNINITIALIZED_VARS = YES; GCC_WARN_UNUSED_FUNCTION = YES; GCC_WARN_UNUSED_VARIABLE = YES; IPHONEOS_DEPLOYMENT_TARGET = 14.0; MTL_ENABLE_DEBUG_INFO = INCLUDE_SOURCE; MTL_FAST_MATH = YES; ONLY_ACTIVE_ARCH = YES; SDKROOT = iphoneos; SWIFT_ACTIVE_COMPILATION_CONDITIONS = DEBUG; SWIFT_OPTIMIZATION_LEVEL = "-Onone"; }; name = Debug; };
		FA0001DF2BD5A1C40027F4A6 /* Release */ = {isa = XCBuildConfiguration; buildSettings = {ALWAYS_SEARCH_USER_PATHS = NO; CLANG_ANALYZER_NONNULL = YES; CLANG_ANALYZER_NUMBER_OBJECT_CONVERSION = YES_AGGRESSIVE; CLANG_CXX_LANGUAGE_DIALECT = "c++20"; CLANG_CXX_LIBRARY = "libc++"; CLANG_ENABLE_MODULES = YES; CLANG_ENABLE_OBJC_ARC = YES; CLANG_ENABLE_OBJC_WEAK = YES; CLANG_WARN_BLOCK_CAPTURE_AUTORELEASING = YES; CLANG_WARN_BOOL_CONVERSION = YES; CLANG_WARN_COMMA = YES; CLANG_WARN_CONSTANT_CONVERSION = YES; CLANG_WARN_DEPRECATED_OBJC_IMPLEMENTATIONS = YES; CLANG_WARN_DIRECT_OBJC_ISA_USAGE = YES_ERROR; CLANG_WARN_DOCUMENTATION_COMMENTS = YES; CLANG_WARN_EMPTY_BODY = YES; CLANG_WARN_ENUM_CONVERSION = YES; CLANG_WARN_INFINITE_RECURSION = YES; CLANG_WARN_INT_CONVERSION = YES; CLANG_WARN_NON_LITERAL_NULL_CONVERSION = YES; CLANG_WARN_OBJC_IMPLICIT_RETAIN_SELF = YES; CLANG_WARN_OBJC_LITERAL_CONVERSION = YES; CLANG_WARN_OBJC_ROOT_CLASS = YES_ERROR; CLANG_WARN_QUOTED_INCLUDE_IN_FRAMEWORK_HEADER = YES; CLANG_WARN_RANGE_LOOP_ANALYSIS = YES; CLANG_WARN_STRICT_PROTOTYPES = YES; CLANG_WARN_SUSPICIOUS_MOVE = YES; CLANG_WARN_SUSPICIOUS_IMPLICIT_CONVERSION = YES; CLANG_WARN_UNREACHABLE_CODE = YES; CLANG_WARN__DUPLICATE_METHOD_MATCH = YES; COPY_PHASE_STRIP = NO; DEBUG_INFORMATION_FORMAT = "dwarf-with-dsym"; ENABLE_NS_ASSERTIONS = NO; ENABLE_STRICT_OBJC_MSGSEND = YES; GCC_C_LANGUAGE_DIALECT = gnu99; GCC_NO_COMMON_BLOCKS = YES; GCC_OPTIMIZE_FOR_SIZE = YES; GCC_PREPROCESSOR_DEFINITIONS = "$(inherited)"; GCC_WARN_64_TO_32_BIT_CONVERSION = YES; GCC_WARN_ABOUT_RETURN_TYPE = YES_ERROR; GCC_WARN_UNDECLARED_SELECTOR = YES; GCC_WARN_UNINITIALIZED_VARS = YES; GCC_WARN_UNUSED_FUNCTION = YES; GCC_WARN_UNUSED_VARIABLE = YES; IPHONEOS_DEPLOYMENT_TARGET = 14.0; MTL_ENABLE_DEBUG_INFO = NO; MTL_FAST_MATH = YES; SDKROOT = iphoneos; SWIFT_COMPILATION_MODE = wholemodule; SWIFT_OPTIMIZATION_LEVEL = "-O"; VALIDATE_PRODUCT = YES; }; name = Release; };
		FA0001E02BD5A1C40027F4A6 /* Debug */ = {isa = XCBuildConfiguration; buildSettings = {ASSETCATALOG_COMPILER_APPICON_NAME = AppIcon; ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME = AccentColor; CODE_SIGN_STYLE = Automatic; CURRENT_PROJECT_VERSION = 1; GCC_PREPROCESSOR_DEFINITIONS = "$(inherited)"; GENERATE_INFOPLIST_FILE = NO; INFOPLIST_FILE = "TrustNetValidator/Info.plist"; INFOPLIST_KEY_CFBundleExecutable = "$(EXECUTABLE_NAME)"; INFOPLIST_KEY_UIApplicationSceneManifest = "{UIApplicationSceneManifestDelegateClassName = \"\"; UIApplicationSupportsMultipleScenes = YES; UISceneConfigurations = @{UIWindowSceneSessionRoleApplication = (@{UISceneConfigurationName = Default; UISceneDelegateClassName = \"\"; });  }; }"; INFOPLIST_KEY_UILaunchScreen_Generation = YES; INFOPLIST_KEY_UISupportedInterfaceOrientations_iPad = "UIInterfaceOrientationPortrait UIInterfaceOrientationPortraitUpsideDown UIInterfaceOrientationLandscapeLeft UIInterfaceOrientationLandscapeRight"; INFOPLIST_KEY_UISupportedInterfaceOrientations_iPhone = "UIInterfaceOrientationPortrait UIInterfaceOrientationLandscapeLandscapeLeft UIInterfaceOrientationLandscapeLandscapeRight"; LD_RUNPATH_SEARCH_PATHS = "$(inherited) @executable_path/Frameworks"; MARKETING_VERSION = 1.0; PRODUCT_BUNDLE_IDENTIFIER = "com.trustnet.validator"; PRODUCT_NAME = "$(TARGET_NAME)"; SWIFT_VERSION = 5.0; TARGETED_DEVICE_FAMILY = "1,2"; }; name = Debug; };
		FA0001E12BD5A1C40027F4A6 /* Release */ = {isa = XCBuildConfiguration; buildSettings = {ASSETCATALOG_COMPILER_APPICON_NAME = AppIcon; ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME = AccentColor; CODE_SIGN_STYLE = Automatic; CURRENT_PROJECT_VERSION = 1; GCC_PREPROCESSOR_DEFINITIONS = "$(inherited)"; GENERATE_INFOPLIST_FILE = NO; INFOPLIST_FILE = "TrustNetValidator/Info.plist"; INFOPLIST_KEY_CFBundleExecutable = "$(EXECUTABLE_NAME)"; INFOPLIST_KEY_UIApplicationSceneManifest = "{UIApplicationSceneManifestDelegateClassName = \"\"; UIApplicationSupportsMultipleScenes = YES; UISceneConfigurations = @{UIWindowSceneSessionRoleApplication = (@{UISceneConfigurationName = Default; UISceneDelegateClassName = \"\"; });  }; }"; INFOPLIST_KEY_UILaunchScreen_Generation = YES; INFOPLIST_KEY_UISupportedInterfaceOrientations_iPad = "UIInterfaceOrientationPortrait UIInterfaceOrientationPortraitUpsideDown UIInterfaceOrientationLandscapeLeft UIInterfaceOrientationLandscapeRight"; INFOPLIST_KEY_UISupportedInterfaceOrientations_iPhone = "UIInterfaceOrientationPortrait UIInterfaceOrientationLandscapeLandscapeLeft UIInterfaceOrientationLandscapeLandscapeRight"; LD_RUNPATH_SEARCH_PATHS = "$(inherited) @executable_path/Frameworks"; MARKETING_VERSION = 1.0; PRODUCT_BUNDLE_IDENTIFIER = "com.trustnet.validator"; PRODUCT_NAME = "$(TARGET_NAME)"; SWIFT_VERSION = 5.0; TARGETED_DEVICE_FAMILY = "1,2"; }; name = Release; };
	};
	rootObject = FA0001BA2BD5A1C40027F4A6;
}
"""

# Write the file
output_path = 'iOS-App.xcodeproj/project.pbxproj'
os.makedirs(os.path.dirname(output_path), exist_ok=True)

with open(output_path, 'w') as f:
    f.write(pbxproj_content)

print(f"✓ Generated {output_path}")
